version: "3"
services:
  hub:
    image: selenium/hub:4.1.0
    # ports:
    #   - "3333:4444"
  chrome:
    image: selenium/node-chrome:4.1.0
    shm_size: '2g'        
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  firefox:
    image: selenium/node-firefox:4.1.0
    shm_size: '2g'   
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  search-module1:
    image: janeuniqacc/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=hub
      - BROWSER=firefox
      - MODULE=search-module.xml
    volumes:
      - ./test-search-result1:/usr/share/udemy/test-output
  # search-module2:
  #   image: janeuniqacc/selenium-docker
  #   depends_on:
  #     - chrome
  #     - firefox
  #   environment:
  #     - HUB_HOST=hub
  #     - BROWSER=chrome
  #     - MODULE=search-module.xml
  #   volumes:
  #     - ./test-search-result2:/usr/share/udemy/test-output
  book-flight-module1:
    image: janeuniqacc/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=hub
      - BROWSER=chrome
      - MODULE=book-flight-module.xml
    volumes:
      - ./test-book-result1:/usr/share/udemy/test-output
  # book-flight-module2:
  #   image: janeuniqacc/selenium-docker
  #   depends_on:
  #     - chrome
  #     - firefox
  #   environment:
  #     - HUB_HOST=hub
  #     - BROWSER=firefox
  #     - MODULE=book-flight-module.xml
  #   volumes:
  #     - ./test-book-result2:/usr/share/udemy/test-output